# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eca2a34bbc4269c66f874d8866cfa172180a7c6c0b7d8defbbc2884bfc66aedff5e69c879cd1434ab43f1644c163dcd4931c9aae5391ebaf2c300fe06383c294

test:
  secret_key_base: 43965e050c597997958ca7d0d88885de0e509bb09c17f047ee0402fa30e5d693f9cb757b4f18ebd4814ad31c968db26ce183955a094a4331b9be5726bd77a754

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
